### ISSUE TITLE
Calling Delete raises KeyNotFound exception

### ISSUE THREAD

**Issue by Thraka** [thelinuxlich/artemis_CSharp#100]
I'm calling delete in my system processor

```csharp
    public class ExpiredObjectSystem : EntityComponentProcessingSystem<Components.DistanceExpireComponent, Components.PositionComponent>
    {
        public override void Process(Entity entity, DistanceExpireComponent expire, PositionComponent position)
        {
            if (expire.CheckExpired(entity, position.MapPosition))
                entity.Delete();
        }
    }
```

I get this error: {"The given key was not present in the dictionary."}

What am I doing wrong?

**Comment by Maximusya** [comment]
Stack trace would help.

There is no Dictionary lookups in the process of entity.Delete().

**Comment by Thraka** [comment]
Sorry, here you go

```
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Artemis.Manager.EntityManager.EntityManagerRemovedComponentEvent(Entity entity, IComponent component)
   at Artemis.Manager.EntityManager.RemoveComponentsOfEntity(Entity entity)
   at Artemis.Manager.EntityManager.Remove(Entity entity)
   at Artemis.EntityWorld.Update(Int64 deltaTicks)
   at BeyondVoyage.Program.Engine_EngineUpdated(Object sender, EventArgs e) in E:\Code\Gits\Ensign\BeyondVoyage\Program.cs:line 128
   at SadConsole.Engine.Update(GameTime gameTime, Boolean windowIsActive)
   at SadConsole.EngineGameComponent.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<.cctor>b__19(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at SadConsole.Engine.Run()
   at BeyondVoyage.Program.Main(String[] args) in E:\Code\Gits\Ensign\BeyondVoyage\Program.cs:line 24
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Thraka** [comment]
I was using a ComponentPoolable on a component which was on an entity. The component was never added to a pool.

Failed on this line: https://github.com/thelinuxlich/artemis_CSharp/blob/master/Artemis_XNA_INDEPENDENT/EntityWorld.cs#L256

**Comment by Maximusya** [comment]
> The component was never added to a pool.

Do you mean that you DID NOT use `entity.AddComponentFromPool`, but used `entity.AddComponent` to add a component inheriting from `ComponentPoolable`?

Your component that inherits from `ComponentPoolable` is also expected to be marked with `ArtemisComponentPool` attribute.
Also note that in order to use pool-thing you should either create an `EntityWorld` with arguments `processAttributes: true, initializeAll: true` or after ctor call on the instance of your entotyWorld `entityWorld.InitializeAll(processAttributes: true)`

**Comment by Thraka** [comment]
Originally I was using the attribute system but I abandoned it. 

I want to have multiple entity world objects. Basically as my game transitions into different things (like you're in space, now you're on a space station) and the game behaves very different in those scenarios. So many of the systems in one world would be valid in another. I want to essentially enable/disable an entire entity world based on game state.

This means I cannot use any of the attribute systems and I have to add everything by hand. Unfortunately there was no way to use the attribute system and group things together by entity world.

The only C# example I have is the starwarrior game and it's not very comprehensive. So I'm guessing as I build things.

**Comment by Maximusya** [comment]
Multiple entity worlds are OK, manually wiring things up is OK: that's the way we do it too.
Except that we do not use pool-things thus we've never encountered current Artemis limitations regarding ComponentPoolable.

Anyway - do you want to use ComponentPoolable? By manually registering Pools? By using entity.AddComponentFromPool?

If not - simply replace inheritance from ComponentPoolable with implementation if IComponent. And forget about pools for a while - until GC-perfomance really matters.

**Comment by Maximusya** [comment]
Not tested, but here is how you can manually setup ComponentPoolable use in every EntityWorld instance:
```csharp
internal class MyPoolableComponent : ComponentPoolable
{
}
```
```csharp
var entityWorld1 = new EntityWorld();
var myPoolableComponentPool1 = new ComponentPool<ComponentPoolable>(
    initialSize: 100,
    resizeSize: 50,
    resizes: true,
    allocateFunc: _ => new MyPoolableComponent(),
    type: typeof(MyPoolableComponent)
);

entityWorld1.SetPool(typeof(MyPoolableComponent), myPoolableComponentPool1);
```
```csharp
entity.AddComponentFromPool<MyPoolableComponent>();
```

**Comment by Thraka** [comment]
Thanks. I just removed the poolable concept for now.
